version: "3"
services:
  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - nuxt
  nuxt:
    container_name: "nuxt"
    build: .
    ports:
      - "3000:3000"
    restart: always
